-- Queries to check data
-- SELECT * FROM public.account ORDER BY account_id ASC;
-- SELECT * FROM public.classification ORDER BY classification_id ASC;
-- SELECT * FROM public.inventory ORDER BY inv_id ASC;
-- ------------------------------------------------------------------------------------

-- ============================================
-- SAFE MIGRATION SCRIPT: cse340 project schema
-- ============================================

-- 1️⃣  Clean up any previous constraints & tables
-- DO $$
-- BEGIN
--   -- Drop foreign key if it exists
--   IF EXISTS (
--     SELECT 1
--     FROM information_schema.table_constraints
--     WHERE constraint_name = 'fk_classification'
--       AND table_name = 'inventory'
--   ) THEN
--     ALTER TABLE public.inventory DROP CONSTRAINT fk_classification;
--   END IF;
-- EXCEPTION
--   WHEN undefined_table THEN
--     -- Inventory table doesn't exist yet, nothing to drop
--     NULL;
-- END$$;

-- DROP TABLE IF EXISTS public.inventory CASCADE;
-- DROP TABLE IF EXISTS public.classification CASCADE;
-- DROP TABLE IF EXISTS public.account CASCADE;
-- DROP TYPE IF EXISTS public.account_type CASCADE;

-- -- 2️⃣  Re-create ENUM type
-- CREATE TYPE public.account_type AS ENUM ('Client', 'Employee', 'Admin');
-- ALTER TYPE public.account_type OWNER TO dominic340_user;

-- -- 3️⃣  Re-create classification table
-- CREATE TABLE public.classification (
--     classification_id INT GENERATED BY DEFAULT AS IDENTITY,
--     classification_name VARCHAR NOT NULL,
--     CONSTRAINT classification_pk PRIMARY KEY (classification_id)
-- );

-- -- 4️⃣  Re-create inventory table
-- CREATE TABLE public.inventory (
--     inv_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     inv_make VARCHAR NOT NULL,
--     inv_model VARCHAR NOT NULL,
--     inv_year CHAR(4) NOT NULL,
--     inv_description TEXT NOT NULL,
--     inv_image VARCHAR NOT NULL,
--     inv_thumbnail VARCHAR NOT NULL,
--     inv_price NUMERIC(9,0) NOT NULL,
--     inv_miles INTEGER NOT NULL,
--     inv_color VARCHAR NOT NULL,
--     classification_id INTEGER NOT NULL
-- );

-- -- 5️⃣  Re-add foreign key
-- ALTER TABLE public.inventory
--   ADD CONSTRAINT fk_classification
--   FOREIGN KEY (classification_id)
--   REFERENCES public.classification (classification_id)
--   ON UPDATE CASCADE
--   ON DELETE NO ACTION;

-- -- 6️⃣  Re-create account table
-- CREATE TABLE public.account (
--     account_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     account_firstname VARCHAR NOT NULL,
--     account_lastname VARCHAR NOT NULL,
--     account_email VARCHAR NOT NULL,
--     account_password VARCHAR NOT NULL,
--     account_type public.account_type NOT NULL DEFAULT 'Client'
-- );

-- -- 7️⃣  Seed classification data
-- INSERT INTO public.classification (classification_name) VALUES
--   ('Custom'), ('Sport'), ('SUV'), ('Truck'), ('Sedan');

-- -- 8️⃣  Verify
-- SELECT * FROM public.classification ORDER BY classification_id;


-- --
-- -- Database: 'cse 340 project', public schema
-- -- Assignment 2, Task 2
-- --
-- DROP TYPE IF EXISTS public.account_type;
-- --Create client_type data type
-- CREATE TYPE public.account_type AS ENUM
--     ('Client', 'Employee', 'Admin');

-- ALTER TYPE public.account_type
--     OWNER TO dominic340_user;

-- --Table structure for table 'classification'
-- CREATE TABLE public.classification (
--     classification_id INT GENERATED BY DEFAULT AS IDENTITY,
--     classification_name CHARACTER VARYING NOT NULL,
--     CONSTRAINT classification_pk PRIMARY KEY (classification_id)
-- );

-- --Table structure for table 'inventory'
-- CREATE TABLE IF NOT EXISTS public.inventory (
--     inv_id INTEGER VARYING NOT NULL,
--     inv_make CHARACTER VARYING NOT NULL,
--     inv_model CHARACTER VARYING NOT NULL,
--     inv_year CHARACTER (4) NOT NULL,
--     inv_description TEXT NOT NULL,
--     inv_image CHARACTER VARYING NOT NULL,
--     inv_thumbnail CHARACTER VARYING NOT NULL,
--     inv_price NUMERIC(9, 0) NOT NULL,
--     inv_miles INTEGER NOT NULL,
--     inv_color CHARACTER VARYING NOT NULL,
--     classification_id INTEGER NOT NULL,
--     CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
-- );

-- -- Create relationship between 'classification' and 'inventory' tables
-- ALTER TABLE IF EXISTS public.inventory
--     ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
--     REFERENCES public.classification (classification_id) MATCH SIMPLE
--     ON UPDATE CASCADE
--     ON DELETE NO ACTION;

-- -- Table structure for table `account`
-- CREATE TABLE IF NOT EXISTS public.account (
--     account_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
--     account_firstname CHARACTER VARYING NOT NULL,
--     account_lastname CHARACTER VARYING NOT NULL,
--     account_email CHARACTER VARYING NOT NULL,
--     account_password CHARACTER VARYING NOT NULL,
--     account_type account_type NOT NULL DEFAULT 'Client'::account_type,
--     CONSTRAINT account_pkey PRIMARY KEY (account_id)
-- );

-- -- Data for table 'classification'
-- INSERT INTO public.classification (classification_name)
-- VALUES ('Custom'),
--     ('Sport'),
--     ('SUV'),
--     ('Truck'),
--     ('Sedan');

-- SELECT * FROM public.account
-- ORDER BY account_id ASC 

-- SELECT * FROM public.classification
-- ORDER BY classification_id ASC

-- SELECT * FROM public.inventory
-- ORDER BY inv_id ASC 


-- --*************************************
-- --***                               ***
-- --***                               ***
-- --***      This is my samples       ***
-- --***                               ***
-- --***                               ***
-- --*************************************
-- -- --
-- -- -- Database: 'cse 340 project', public schema
-- -- -- Assignment 2, Task 2
-- -- --
-- DROP TYPE IF EXISTS public.account_type CASCADE;
-- --Create client_type data type
-- CREATE TYPE public.account_type AS ENUM
--     ('Client', 'Employee', 'Admin');

-- ALTER TYPE public.account_type
--     OWNER TO dominic340_user;

-- --Table structure for table 'classification'
-- -- CREATE TABLE public.classification (
-- --     classification_id INT GENERATED BY DEFAULT AS IDENTITY,
-- --     classification_name CHARACTER VARYING NOT NULL,
-- --     CONSTRAINT classification_pk PRIMARY KEY (classification_id)
-- -- );
-- CREATE TABLE IF NOT EXISTS public.classification (
--     classification_id INT GENERATED BY DEFAULT AS IDENTITY,
--     classification_name VARCHAR NOT NULL,
--     CONSTRAINT classification_pk PRIMARY KEY (classification_id)
-- );

-- --Table structure for table 'inventory'
-- CREATE TABLE IF NOT EXISTS public.inventory (
--     inv_id INTEGER NOT NULL,
--     inv_make CHARACTER VARYING NOT NULL,
--     inv_model CHARACTER VARYING NOT NULL,
--     inv_year CHARACTER (4) NOT NULL,
--     inv_description TEXT NOT NULL,
--     inv_image CHARACTER VARYING NOT NULL,
--     inv_thumbnail CHARACTER VARYING NOT NULL,
--     inv_price NUMERIC(9, 0) NOT NULL,
--     inv_miles INTEGER NOT NULL,
--     inv_color CHARACTER VARYING NOT NULL,
--     classification_id INTEGER NOT NULL,
--     CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
-- );

-- CREATE relationship BETWEEN classification AND inventory TABLE;
-- ALTER TABLE IF EXISTS public.inventory
--     ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
--     REFERENCES public.classification (classification_id) MATCH SIMPLE
--     ON UPDATE CASCADE
--     ON DELETE NO ACTION;

-- -- ALTER TABLE inventory
-- -- 	ADD CONSTRAINT IF NOT EXISTS fk_classification
-- -- 	FOREIGN KEY (classification_id)
-- -- 	REFERENCES classification (classification_id);

-- -- Table structure for table `account`
-- CREATE TABLE IF NOT EXISTS public.account (
--     account_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
--     account_firstname CHARACTER VARYING NOT NULL,
--     account_lastname CHARACTER VARYING NOT NULL,
--     account_email CHARACTER VARYING NOT NULL,
--     account_password CHARACTER VARYING NOT NULL,
--     account_type account_type NOT NULL DEFAULT 'Client'::account_type,
--     CONSTRAINT account_pkey PRIMARY KEY (account_id)
-- );

-- -- Data for table 'classification'
-- INSERT INTO public.classification (classification_name)
-- VALUES ('Custom'),
--     ('Sport'),
--     ('SUV'),
--     ('Truck'),
--     ('Sedan');

-- SELECT * FROM public.account
-- ORDER BY account_id ASC;

-- SELECT * FROM public.classification
-- ORDER BY classification_id ASC;

-- SELECT * FROM public.inventory
-- ORDER BY inv_id ASC;