-- ------------------------------------------------------------------------------------
-- Database: 'cse 340 project', public schema
-- Assignment 2, Task 2

-- Drop and recreate ENUM type
DROP TYPE IF EXISTS public.account_type CASCADE;
CREATE TYPE public.account_type AS ENUM ('Client', 'Employee', 'Admin');
ALTER TYPE public.account_type OWNER TO abah340_user;

-- Table: classification
CREATE TABLE IF NOT EXISTS public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name VARCHAR NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- Table: inventory
DROP TABLE IF EXISTS public.inventory CASCADE;
CREATE TABLE IF NOT EXISTS public.inventory (
    inv_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    inv_make VARCHAR NOT NULL,
    inv_model VARCHAR NOT NULL,
    inv_year CHAR(4) NOT NULL,
    inv_description TEXT NOT NULL,
    inv_image VARCHAR NOT NULL,
    inv_thumbnail VARCHAR NOT NULL,
    inv_price NUMERIC(9,0) NOT NULL,
    inv_miles INTEGER NOT NULL,
    inv_color VARCHAR NOT NULL,
    classification_id INTEGER NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.table_constraints 
        WHERE constraint_name = 'fk_classification'
          AND table_name = 'inventory'
    ) THEN
        ALTER TABLE public.inventory DROP CONSTRAINT fk_classification;
    END IF;
END$$;

-- 🔗 Create the relationship (foreign key) between classification and inventory
ALTER TABLE IF EXISTS public.inventory
    ADD CONSTRAINT fk_classification
    FOREIGN KEY (classification_id)
    REFERENCES public.classification (classification_id)
    ON UPDATE CASCADE
    ON DELETE NO ACTION;

-- Table: account
CREATE TABLE IF NOT EXISTS public.account (
    account_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_firstname VARCHAR NOT NULL,
    account_lastname VARCHAR NOT NULL,
    account_email VARCHAR NOT NULL,
    account_password VARCHAR NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type
);

-- Seed data for classification
INSERT INTO public.classification (classification_name)
VALUES 
    ('Custom'),
    ('Sport'),
    ('SUV'),
    ('Truck'),
    ('Sedan')
ON CONFLICT DO NOTHING;

--Modify the "GM Hummer" record to read "a huge interior" rather than "small interiors" 
--using a single query
UPDATE public.inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_id = 10;

--Update all records in the inventory table to add "/vehicles" to the middle of the 
--file path in the inv_image and inv_thumbnail columns using a single query.
UPDATE public.inventory
SET 
	inv_image = REPLACE(inv_image, '/image', '/image/vehicle'),
	inv_thumbnail = REPLACE(inv_thumbnail, '/image', '/image/vehicle');
